version: "3.8"

services:
#  vitis-ai:
#    image: amdih/vitis-ai:versal-2ve-release_v6.2_0612
#    container_name: vitis-ai
#    tty: true
#    stdin_open: true
#    volumes:
#      - .:/workspace
#    working_dir: /workspace
#    environment:
#      - USER=root
#    command: /bin/bash

  python-310:
    image: python:3.10.1
    container_name: python-310
    tty: true
    stdin_open: true
    volumes:
      - .:/src
    working_dir: /src
    environment:
      - USER=root
    command: /bin/bash

  hls:
    image: python:3.10.1
    container_name: hls
    tty: true
    stdin_open: true
    volumes:
      - .:/src
    working_dir: /src
    environment:
      - USER=root
    command: /bin/bash